// actionTypes.js

export const FETCH_FRIENDS_SUCCESS = "FETCH_FRIENDS_SUCCESS";
export const FETCH_POSTS_SUCCESS = "FETCH_POSTS_SUCCESS";
export const LIKE_POST_SUCCESS = "LIKE_POST_SUCCESS";
export const UNLIKE_POST_SUCCESS = "UNLIKE_POST_SUCCESS";
export const ADD_COMMENT_SUCCESS = "ADD_COMMENT_SUCCESS";
export const SHOW_COMMENTS_SUCCESS = "SHOW_COMMENTS_SUCCESS";
export const FETCH_COMMENTS_COUNT_SUCCESS = "FETCH_COMMENTS_COUNT_SUCCESS";
